---
name: pre-commit

on:
    workflow_call:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        env:
            PIP_DISABLE_PIP_VERSION_CHECK: 1 # avoids pip upgrade in actions/setup-python@v5
        steps:
            - uses: actions/checkout@v4
            - name: Install poetry
              run: pipx install poetry
            - uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version
                  check-latest: false
                  cache: poetry
            - name: Install dependencies
              run: |
                  poetry install
            - uses: actions/cache@v4
              with:
                  path: ~/.cache/pre-commit
                  key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
            - name: Run pre-commit
              run: |
                  poetry run pre-commit run --show-diff-on-failure --color=always --all-files
