---
name: test

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - name: Set up uv
              run: curl -LsSf https://astral.sh/uv/0.4.4/install.sh | sh

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Run Tests
              run: uv run pytest
