---
name: On PR

on:
    pull_request:
        branches: [main]
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    pre-commit:
        uses: ./.github/workflows/job-pre-commit.yml

    test:
        uses: ./.github/workflows/job-test.yml
        permissions:
            contents: read
            id-token: write
